### ISSUE TITLE
`datasource` shouldn't have an obligatory `location` FK

### ISSUE THREAD

**Issue by cmutel** [BONSAMURAIS/schema#20]
From Slack message by @BenPortner.

@tngTUDOR Please explain the motivation for this, it doesn't seem clear to me.

@boweidema Do you know the status of the provenance ontology? It isn't provided anywhere on the [official repo](https://github.com/BONSAMURAIS/BONSAI-ontology-RDF-framework), and it would be nice to follow the ontology here.

**Comment by tngTUDOR** [comment]
@BenPortner the question is: 
should we associate every data source to a geographical location ?

At the beginning I thought we should, but after a second thought, if a `datasource` describes objects from many different (geographical) locations, then it wouldn't make sense.

**Comment by BenPortner** [comment]
@tngTUDOR 
That's a new train of thought for me. I assumed that the field should describe the `location` of the `datasource`. Now it sounds like the original purpose was for it to be a collection of all the `locations` associated with `activities` in the `datasource`. This could be useful to filter datasources quickly and decide which one is suitable for the user's purpose. Is that what the field is for?

**Comment by cmutel** [comment]
> should we associate every data source to a geographical location ?

No. Locations of activities are defined per activity. 

> Now it sounds like the original purpose was for it to be a collection of all the locations associated with activities in the datasource.

This exists already: 

    select location.label from activity 
    left join activity on activity.location_id = location.id 
    left join datasource on activity.datasource_id = datasource.id 
    where datasource.label = 'foo'

Or, more simply:

    select activity.location_id from activity where activity.datasource_id = x
