### ISSUE TITLE
Need concept of dataset group/collection/database

### ISSUE THREAD

**Issue by cmutel** [BONSAMURAIS/schema#8]
Doesn't seem to be included in the BONSAI ontology (though perhaps implicitly in places like arborist), but quite important for practitioners to know about.

**Comment by cmutel** [comment]
Should include (or make a decision) on the following (including field name and data type, and whether it is required):

- versioning (separate table?)
- URL/URI
- license (separate table?)
- What tables are linked? Flow, flow_object, activity?

**Comment by cmutel** [comment]
See also https://github.com/BONSAMURAIS/schema/issues/9: adapt and add ontology for data provenance.

**Comment by tngTUDOR** [comment]
a better name for URL/URI could be "source"

**Comment by tngTUDOR** [comment]
license could be just a short license name matching to known lists of licenses (I'm thinking of https://tldrlegal.com/ as a strat)

**Comment by cmutel** [comment]
Instead of TLDR legal I think this is better: https://spdx.org/licenses/

**Comment by tngTUDOR** [comment]
Are we going to support multiple Activities and flows belonging to multiple datasources ?

**Comment by cmutel** [comment]
Good question! My initial inclination is to keep things simple, as assume an activity or flow_object or flow belongs to a single datasource unless we find a case where we need to make things more complicated.

**Comment by cmutel** [comment]
Fixed in #13
